export const enum Screens {
  LOGIN_NAVIGATOR = 'LOGIN_NAVIGATOR',
  LOGIN_SCREEN = 'LOGIN_SCREEN',

  APP_NAVIGATOR = 'APP_NAVIGATOR',
  APP_PROJECT_NAVIGATOR = 'APP_PROJECT_NAVIGATOR',
  APP_DAILY_REPORT_NAVIGATOR = 'APP_DAILY_REPORT_NAVIGATOR',
  APP_MONTHLY_REPORT_NAVIGATOR = 'APP_MONTHLY_REPORT_NAVIGATOR',
  APP_SITE_REPORT_NAVIGATOR = 'APP_SITE_REPORT_NAVIGATOR',
  APP_OTHER_NAVIGATOR = 'APP_OTHER_NAVIGATOR',
  APP_PROJECT_SCREEN = 'APP_PROJECT_SCREEN',
  APP_DAILY_REPORT_SCREEN = 'APP_DAILY_REPORT_SCREEN',
  APP_MONTHLY_REPORT_SCREEN = 'APP_MONTHLY_REPORT_SCREEN',
  APP_SITE_REPORT_SCREEN = 'APP_SITE_REPORT_SCREEN',
  APP_OTHER_SCREEN = 'APP_OTHER_SCREEN',
}
