export const enum Screens {
  LOADING_SCREEN = 'LOADING_SCREEN',

  LOGIN_NAVIGATOR = 'LOGIN_NAVIGATOR',
  LOGIN_SCREEN = 'LOGIN_SCREEN',

  APP_MENU_NAVIGATOR = 'APP_MENU_NAVIGATOR',
  APP_NAVIGATOR = 'APP_NAVIGATOR',

  APP_PROJECT_NAVIGATOR = 'APP_PROJECT_NAVIGATOR',
  APP_PROJECT_LIST = 'APP_PROJECT_LIST',
  APP_PROJECT_UPSERT = 'APP_PROJECT_UPSERT',

  APP_DAILY_REPORT_NAVIGATOR = 'APP_DAILY_REPORT_NAVIGATOR',
  APP_DAILY_REPORT__PROJECT_LIST_SCREEN = "APP_DAILY_REPORT__PROJECT_LIST_SCREEN",
  APP_DAILY_REPORT__REPORT_LIST_SCREEN = 'APP_DAILY_REPORT__REPORT_LIST_SCREEN',
  APP_DAILY_REPORT__UPSERT_SCREEN = "APP_DAILY_REPORT__UPSERT_SCREEN",

  APP_MONTHLY_REPORT_NAVIGATOR = 'APP_MONTHLY_REPORT_NAVIGATOR',
  APP_MONTHLY_REPORT__PROJECT_LIST_SCREEN = 'APP_MONTHLY_REPORT__PROJECT_LIST_SCREEN',
  APP_MONTHLY_REPORT__REPORT_LIST_SCREEN = "APP_MONTHLY_REPORT__REPORT_LIST_SCREEN",
  APP_MONTHLY_REPORT__UPSERT_SCREEN = "APP_MONTHLY_REPORT__UPSERT_SCREEN",

  APP_SITE_REPORT_NAVIGATOR = 'APP_SITE_REPORT_NAVIGATOR',
  APP_SITE_REPORT__PROJECT_LIST_SCREEN = 'APP_SITE_REPORT__PROJECT_LIST_SCREEN',
  APP_SITE_REPORT__REPORT_LIST_SCREEN = "APP_SITE_REPORT__REPORT_LIST_SCREEN",
  APP_SITE_REPORT__UPSERT_SCREEN = "APP_SITE_REPORT__UPSERT_SCREEN",

  APP_FINANCIAL_NAVIGATOR = "APP_FINANCIAL_NAVIGATOR",
  APP_FINANCIAL_SCREEN = "APP_FINANCIAL_SCREEN",
  APP_FINANCIAL_INVOICE_LIST = "APP_FINANCIAL_INVOICE_LIST",
  APP_FINANCIAL_INVOICE_UPSERT = "APP_FINANCIAL_INVOICE_UPSERT",
  APP_FINANCIAL_COST_LIST = "APP_FINANCIAL_COST_LIST",
  APP_FINANCIAL_COST_UPSERT = "APP_FINANCIAL_COST_UPSERT",
  APP_FINANCIAL_RECEIPT_LIST = "APP_FINANCIAL_RECEIPT_LIST",
  APP_FINANCIAL_RECEIPT_UPSERT = "APP_FINANCIAL_RECEIPT_UPSERT",

  APP_SETTINGS_NAVIGATOR = 'APP_SETTINGS_NAVIGATOR',
  APP_SETTINGS_SCREEN = 'APP_SETTINGS_SCREEN',

  APP_EMPLOYEE_LIST = 'APP_EMPLOYEE_LIST',
  APP_EMPLOYEE_UPSERT = 'APP_EMPLOYEE_UPSERT',

  APP_ACTIVITY_TEMPLATE_LIST = 'APP_ACTIVITY_TEMPLATE_LIST',
  APP_ACTIVITY_TEMPLATE_UPSERT = 'APP_ACTIVITY_TEMPLATE_UPSERT',

  APP_USER_LIST = 'APP_USER_LIST',
  APP_USER_UPSERT = 'APP_USER_UPSERT',

  APP_CLIENT_LIST = "APP_CLIENT_LIST",
  APP_CLIENT_UPSERT = "APP_CLIENT_UPSERT",

  APP_SUPPLIER_LIST = "APP_SUPPLIER_LIST",
  APP_SUPPLIER_UPSERT = "APP_SUPPLIER_UPSERT",

  APP_CONTRACT_LIST = "APP_CONTRACTS_LIST",
  APP_CONTRACT_UPSERT = "APP_CONTRACTS_UPSERT",

  APP_PRODUCT_LIST = "APP_PRODUCT_LIST",
  APP_PRODUCT_UPSERT = "APP_PRODUCT_UPSERT"
}
