export const enum Screens {
  LOADING_SCREEN = 'LOADING_SCREEN',

  LOGIN_NAVIGATOR = 'LOGIN_NAVIGATOR',
  LOGIN_SCREEN = 'LOGIN_SCREEN',

  APP_MENU_NAVIGATOR = 'APP_MENU_NAVIGATOR',
  APP_NAVIGATOR = 'APP_NAVIGATOR',

  APP_PROJECT_NAVIGATOR = 'APP_PROJECT_NAVIGATOR',
  APP_PROJECT_LIST = 'APP_PROJECT_LIST',
  APP_PROJECT_UPSERT = 'APP_PROJECT_UPSERT',

  APP_DAILY_REPORT_NAVIGATOR = 'APP_DAILY_REPORT_NAVIGATOR',
  APP_DAILY_REPORT__PROJECT_LIST_SCREEN = "APP_DAILY_REPORT__PROJECT_LIST_SCREEN",
  APP_DAILY_REPORT__REPORT_LIST_SCREEN = 'APP_DAILY_REPORT__REPORT_LIST_SCREEN',
  APP_DAILY_REPORT__UPSERT_SCREEN = "APP_DAILY_REPORT__UPSERT_SCREEN",

  APP_MONTHLY_REPORT_NAVIGATOR = 'APP_MONTHLY_REPORT_NAVIGATOR',
  APP_MONTHLY_REPORT__PROJECT_LIST_SCREEN = 'APP_MONTHLY_REPORT__PROJECT_LIST_SCREEN',
  APP_MONTHLY_REPORT__REPORT_LIST_SCREEN = "APP_MONTHLY_REPORT__REPORT_LIST_SCREEN",
  APP_MONTHLY_REPORT__UPSERT_SCREEN = "APP_MONTHLY_REPORT__UPSERT_SCREEN",

  APP_SITE_REPORT_NAVIGATOR = 'APP_SITE_REPORT_NAVIGATOR',
  APP_SITE_REPORT__PROJECT_LIST_SCREEN = 'APP_SITE_REPORT__PROJECT_LIST_SCREEN',
  APP_SITE_REPORT__REPORT_LIST_SCREEN = "APP_SITE_REPORT__REPORT_LIST_SCREEN",
  APP_SITE_REPORT__UPSERT_SCREEN = "APP_SITE_REPORT__UPSERT_SCREEN",

  APP_SETTINGS_NAVIGATOR = 'APP_SETTINGS_NAVIGATOR',
  APP_SETTINGS_SCREEN = 'APP_SETTINGS_SCREEN',

  APP_EMPLOYEE_LIST = 'APP_EMPLOYEE_LIST',
  APP_EMPLOYEE_UPSERT = 'APP_EMPLOYEE_UPSERT',

  APP_ACTIVITY_TEMPLATE_LIST = 'APP_ACTIVITY_TEMPLATE_LIST',
  APP_ACTIVITY_TEMPLATE_UPSERT = 'APP_ACTIVITY_TEMPLATE_UPSERT',
}
